# Specify a custom Vagrant box for the demo
DEMO_BOX_NAME = ENV['DEMO_BOX_NAME'] || "danielec/stretch64"

# Vagrantfile API/syntax version.
# NB: Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = DEMO_BOX_NAME
  config.vm.provision "shell", path: "scripts/consul.sh", run: "always"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--groups", "/consul_lab"]
  end

  #consul server
  (1..3).each do |i|
    config.vm.define vm_name = "consul#{i}" do |server|
        server.vm.hostname = vm_name
        server.vm.network "private_network", ip: "172.20.20.1#{i}"

    end
  end


  # Redis Server
  config.vm.define "redis-server" do |rs|
      rs.vm.hostname = "redis"
      rs.vm.network "private_network", ip: "172.20.20.31"
      rs.vm.provision "shell", path: "scripts/redis.sh", run: "always"                   
  end

  # Modern App
  config.vm.define "modern-app" do |ma|
      ma.vm.hostname = "modern"
      ma.vm.network "private_network", ip: "172.20.20.32"
      ma.vm.provision "shell", path: "scripts/golang.sh", run: "always"  
  end

end
